/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Pestañas;
import javax.swing.JOptionPane;
import javax.swing.JPasswordField;

/**
 *
 * @author yanar
 */
public class LoginAdmin extends javax.swing.JFrame {

    private javax.swing.JTextField jTextFieldNombreUsuario;
    private javax.swing.JPasswordField jPasswordFieldContrasena;
    
    /**
     * Creates new form LoginAdmin
     */
    public LoginAdmin() {
        initComponents();
        jTextFieldNombreUsuario = new javax.swing.JTextField();
        jPasswordFieldContrasena = new javax.swing.JPasswordField();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlFondo = new javax.swing.JPanel();
        pnlAdmin = new javax.swing.JPanel();
        txtUsuarioAdmin = new javax.swing.JTextField();
        lbUsuarioA = new javax.swing.JLabel();
        lbContraseñaA = new javax.swing.JLabel();
        btnIngresar = new javax.swing.JButton();
        txtContraseñaAdmin = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Inicio Sesión");
        setResizable(false);

        pnlFondo.setPreferredSize(new java.awt.Dimension(600, 300));
        pnlFondo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnlAdmin.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Admin", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION));
        pnlAdmin.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        pnlAdmin.add(txtUsuarioAdmin, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 70, 160, -1));

        lbUsuarioA.setText("Usuario Admin");
        pnlAdmin.add(lbUsuarioA, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 50, -1, -1));

        lbContraseñaA.setText("Contraseña");
        pnlAdmin.add(lbContraseñaA, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 110, -1, -1));

        btnIngresar.setText("Ingresar");
        btnIngresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIngresarActionPerformed(evt);
            }
        });
        pnlAdmin.add(btnIngresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 170, -1, -1));
        pnlAdmin.add(txtContraseñaAdmin, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 130, 160, -1));

        pnlFondo.add(pnlAdmin, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 30, 390, 240));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlFondo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlFondo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnIngresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIngresarActionPerformed
        try {
            String nombreUsuario = jTextFieldNombreUsuario.getText();
            String contrasena = new String(jPasswordFieldContrasena.getPassword());

            Conexion.CAdmin objetoLoginA = new Conexion.CAdmin();

            if (objetoLoginA.validarUsuarioAdmin(txtUsuarioAdmin, txtContraseñaAdmin)){
                dispose();

                FrameAdmin objetoInicio = new FrameAdmin();
                objetoInicio.setLocationRelativeTo(null);
                objetoInicio.setVisible(true);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error: " + e.getMessage(), "Error de autenticación", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnIngresarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                LoginAdmin objetoLoginA = new LoginAdmin();
                objetoLoginA.setLocationRelativeTo(null);
                objetoLoginA.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnIngresar;
    private javax.swing.JLabel lbContraseñaA;
    private javax.swing.JLabel lbUsuarioA;
    private javax.swing.JPanel pnlAdmin;
    private javax.swing.JPanel pnlFondo;
    private javax.swing.JPasswordField txtContraseñaAdmin;
    private javax.swing.JTextField txtUsuarioAdmin;
    // End of variables declaration//GEN-END:variables
}
